export const SETTINGS = {
  world: {
    size: 360,
    terrainSegments: 160,
    fogColor: 0xd7c69d,
    skyTopColor: 0x6f95b4,
    skyHorizonColor: 0xf2bd7d,
    skyGroundColor: 0x587247,
    groundLowColor: 0x3f5a36,
    groundMidColor: 0x6f8a4e,
    groundHighColor: 0xa9965e,
    groundPathColor: 0xb07e4c,
    dayNight: {
      cycleDuration: 420,
      startTime: 0.28,
      nightAlertMultiplier: 1.16,
    },
  },
  player: {
    radius: 0.42,
    height: 1.82,
    walkSpeed: 5.6,
    sprintSpeed: 9.2,
    jumpVelocity: 7.6,
    gravity: 22,
    groundSnap: 0.18,
    maxGroundStep: 0.62,
    groundFollow: 22,
    acceleration: 16,
    airAcceleration: 5,
    damping: 12,
    stamina: 100,
  },
  camera: {
    mouseSensitivity: 0.0024,
    minPitch: -1.05,
    maxPitch: 1.05,
    thirdPersonDistance: 8.4,
    thirdPersonAimDistance: 6.4,
    thirdPersonHeight: 1.55,
    thirdPersonShoulderOffset: 0.92,
    thirdPersonAimShoulderOffset: 1.45,
    thirdPersonLookAhead: 5.2,
    firstPersonHeight: 1.63,
    firstPersonAimSideOffset: 0.08,
    firstPersonAimFov: 52,
    thirdPersonAimFov: 58,
  },
  archery: {
    baseDrawTime: 1.35,
    drawTime: 1.35,
    minSpeed: 22,
    maxSpeed: 66,
    gravity: 19,
    arrowLife: 8,
    stuckArrowLife: 3,
    arrowLength: 1.35,
    aimLift: 0.035,
    firstPersonBowOffset: { x: 0.5, y: -0.28, z: -0.78 },
    thirdPersonBowOffset: { x: 0.42, y: 1.06, z: 0.16 },
    arrowTypes: {
      standard: { name: "Standard Arrow", color: 0xffe3a0, damageMultiplier: 1, rangeMultiplier: 1 },
      fire: { name: "Fire Arrow", color: 0xff8a3d, damageMultiplier: 1.08, rangeMultiplier: 0.98, burnDuration: 3.8 },
      ice: { name: "Ice Arrow", color: 0x8ddcff, damageMultiplier: 0.92, rangeMultiplier: 1, slowDuration: 3.2 },
      explosive: { name: "Explosive Arrow", color: 0xffcf5f, damageMultiplier: 0.82, rangeMultiplier: 0.92, radius: 4.2 },
    },
  },
  weather: {
    transitionSpeed: 0.14,
    changeInterval: 42,
    types: ["clear", "cloudy", "light-rain", "fog"],
  },
  enemies: {
    arrowDamage: 34,
    healthBarAimDot: 0.975,
    healthBarDistance: 32,
    verticalReach: 2.35,
    verticalHitReach: 3.15,
    meleeRange: 1.25,
    playerDamageCooldown: 0.85,
    contactDamage: 8,
    elevatedGuardDistance: 2.25,
    nightCloseNoticeDistance: 4.5,
    crawler: {
      health: 100,
      patrolSpeed: 0.75,
      chaseSpeed: 1.65,
      noticeDistance: 13,
      leashRadius: 13,
      bodyRadius: 0.65,
      damage: 7,
    },
    wolf: {
      health: 70,
      patrolSpeed: 1.25,
      chaseSpeed: 3.35,
      noticeDistance: 17,
      leashRadius: 15,
      bodyRadius: 0.48,
      damage: 9,
    },
    snowWolf: {
      health: 95,
      patrolSpeed: 1.15,
      chaseSpeed: 3.55,
      noticeDistance: 18,
      leashRadius: 18,
      bodyRadius: 0.52,
      damage: 10,
    },
    iceStag: {
      health: 120,
      patrolSpeed: 0.95,
      chaseSpeed: 2.75,
      noticeDistance: 14,
      leashRadius: 16,
      bodyRadius: 0.62,
      damage: 10,
    },
    frostCrawler: {
      health: 130,
      patrolSpeed: 0.68,
      chaseSpeed: 1.85,
      noticeDistance: 14,
      leashRadius: 15,
      bodyRadius: 0.7,
      damage: 8,
    },
    cliffRaptor: {
      health: 90,
      patrolSpeed: 1.05,
      chaseSpeed: 3.15,
      noticeDistance: 18,
      leashRadius: 19,
      bodyRadius: 0.5,
      damage: 10,
    },
    tideCrawler: {
      health: 115,
      patrolSpeed: 0.72,
      chaseSpeed: 1.95,
      noticeDistance: 14,
      leashRadius: 16,
      bodyRadius: 0.68,
      damage: 8,
    },
    windGull: {
      health: 58,
      patrolSpeed: 1.55,
      chaseSpeed: 3.75,
      noticeDistance: 20,
      leashRadius: 22,
      bodyRadius: 0.38,
      damage: 7,
    },
    shellbackBeast: {
      health: 155,
      patrolSpeed: 0.55,
      chaseSpeed: 1.55,
      noticeDistance: 13,
      leashRadius: 15,
      bodyRadius: 0.82,
      damage: 11,
    },
    mistStag: {
      health: 125,
      patrolSpeed: 0.9,
      chaseSpeed: 2.65,
      noticeDistance: 16,
      leashRadius: 18,
      bodyRadius: 0.6,
      damage: 9,
    },
    glowFox: {
      health: 68,
      patrolSpeed: 1.35,
      chaseSpeed: 3.45,
      noticeDistance: 17,
      leashRadius: 17,
      bodyRadius: 0.42,
      damage: 8,
    },
    rootBeast: {
      health: 150,
      patrolSpeed: 0.58,
      chaseSpeed: 1.72,
      noticeDistance: 14,
      leashRadius: 16,
      bodyRadius: 0.82,
      damage: 12,
    },
    forestWisp: {
      health: 52,
      patrolSpeed: 1.2,
      chaseSpeed: 2.8,
      noticeDistance: 18,
      leashRadius: 18,
      bodyRadius: 0.34,
      damage: 7,
    },
    marshStalker: {
      health: 105,
      patrolSpeed: 0.9,
      chaseSpeed: 2.85,
      noticeDistance: 16,
      leashRadius: 18,
      bodyRadius: 0.52,
      damage: 10,
    },
    mudCrawler: {
      health: 135,
      patrolSpeed: 0.62,
      chaseSpeed: 1.85,
      noticeDistance: 14,
      leashRadius: 16,
      bodyRadius: 0.72,
      damage: 9,
    },
    mireBat: {
      health: 62,
      patrolSpeed: 1.45,
      chaseSpeed: 3.5,
      noticeDistance: 19,
      leashRadius: 20,
      bodyRadius: 0.34,
      damage: 8,
    },
    swampHornbeast: {
      health: 165,
      patrolSpeed: 0.72,
      chaseSpeed: 2.25,
      noticeDistance: 15,
      leashRadius: 17,
      bodyRadius: 0.78,
      damage: 12,
    },
    canyonStrider: {
      health: 92,
      patrolSpeed: 1.15,
      chaseSpeed: 3.05,
      noticeDistance: 18,
      leashRadius: 20,
      bodyRadius: 0.46,
      damage: 9,
    },
    rockbackRam: {
      health: 150,
      patrolSpeed: 0.82,
      chaseSpeed: 2.45,
      noticeDistance: 15,
      leashRadius: 18,
      bodyRadius: 0.68,
      damage: 12,
    },
    dustRaptor: {
      health: 82,
      patrolSpeed: 1.28,
      chaseSpeed: 3.55,
      noticeDistance: 20,
      leashRadius: 21,
      bodyRadius: 0.46,
      damage: 10,
    },
    sandViper: {
      health: 70,
      patrolSpeed: 1.05,
      chaseSpeed: 3.1,
      noticeDistance: 16,
      leashRadius: 16,
      bodyRadius: 0.34,
      damage: 8,
    },
    ashHound: {
      health: 92,
      patrolSpeed: 1.05,
      chaseSpeed: 3.25,
      noticeDistance: 20,
      leashRadius: 21,
      bodyRadius: 0.46,
      damage: 11,
    },
    emberDrake: {
      health: 86,
      patrolSpeed: 1.22,
      chaseSpeed: 3.45,
      noticeDistance: 22,
      leashRadius: 22,
      bodyRadius: 0.44,
      damage: 11,
    },
    magmaCrawler: {
      health: 104,
      patrolSpeed: 0.82,
      chaseSpeed: 2.5,
      noticeDistance: 16,
      leashRadius: 18,
      bodyRadius: 0.52,
      damage: 10,
    },
    firehornBeast: {
      health: 128,
      patrolSpeed: 0.78,
      chaseSpeed: 2.45,
      noticeDistance: 18,
      leashRadius: 20,
      bodyRadius: 0.62,
      damage: 13,
    },
    astralStag: {
      health: 150,
      patrolSpeed: 1.05,
      chaseSpeed: 3.15,
      noticeDistance: 22,
      leashRadius: 24,
      bodyRadius: 0.62,
      damage: 14,
    },
    crystalWyrm: {
      health: 175,
      patrolSpeed: 0.72,
      chaseSpeed: 2.45,
      noticeDistance: 21,
      leashRadius: 24,
      bodyRadius: 0.76,
      damage: 15,
    },
    starboundHunter: {
      health: 135,
      patrolSpeed: 1.18,
      chaseSpeed: 3.35,
      noticeDistance: 24,
      leashRadius: 25,
      bodyRadius: 0.48,
      damage: 16,
    },
    celestialWisp: {
      health: 88,
      patrolSpeed: 1.38,
      chaseSpeed: 3.55,
      noticeDistance: 25,
      leashRadius: 26,
      bodyRadius: 0.36,
      damage: 12,
    },
    moonclawBeast: {
      health: 190,
      patrolSpeed: 0.82,
      chaseSpeed: 2.75,
      noticeDistance: 22,
      leashRadius: 24,
      bodyRadius: 0.78,
      damage: 18,
    },
    plainsStag: {
      health: 145,
      patrolSpeed: 1.18,
      chaseSpeed: 3.25,
      noticeDistance: 24,
      leashRadius: 28,
      bodyRadius: 0.58,
      damage: 14,
    },
    riverfang: {
      health: 125,
      patrolSpeed: 1.08,
      chaseSpeed: 3.45,
      noticeDistance: 24,
      leashRadius: 26,
      bodyRadius: 0.48,
      damage: 16,
    },
    skyHawk: {
      health: 86,
      patrolSpeed: 1.42,
      chaseSpeed: 3.8,
      noticeDistance: 26,
      leashRadius: 30,
      bodyRadius: 0.36,
      damage: 12,
    },
    frontierWolf: {
      health: 135,
      patrolSpeed: 1.18,
      chaseSpeed: 3.55,
      noticeDistance: 25,
      leashRadius: 28,
      bodyRadius: 0.48,
      damage: 16,
    },
    stonehideGrazer: {
      health: 205,
      patrolSpeed: 0.72,
      chaseSpeed: 2.35,
      noticeDistance: 21,
      leashRadius: 25,
      bodyRadius: 0.78,
      damage: 18,
    },
    kingdomSentinel: {
      health: 165,
      patrolSpeed: 0.82,
      chaseSpeed: 2.55,
      noticeDistance: 22,
      leashRadius: 26,
      bodyRadius: 0.58,
      damage: 17,
    },
    ruinStalker: {
      health: 135,
      patrolSpeed: 1.12,
      chaseSpeed: 3.35,
      noticeDistance: 24,
      leashRadius: 28,
      bodyRadius: 0.5,
      damage: 17,
    },
    archiveWisp: {
      health: 96,
      patrolSpeed: 1.36,
      chaseSpeed: 3.4,
      noticeDistance: 25,
      leashRadius: 28,
      bodyRadius: 0.36,
      damage: 13,
    },
    stoneGuardian: {
      health: 220,
      patrolSpeed: 0.62,
      chaseSpeed: 2.1,
      noticeDistance: 21,
      leashRadius: 25,
      bodyRadius: 0.82,
      damage: 20,
    },
    skyWyrm: {
      health: 150,
      patrolSpeed: 1.18,
      chaseSpeed: 3.35,
      noticeDistance: 26,
      leashRadius: 30,
      bodyRadius: 0.52,
      damage: 17,
    },
    astralHunter: {
      health: 155,
      patrolSpeed: 1.12,
      chaseSpeed: 3.45,
      noticeDistance: 25,
      leashRadius: 28,
      bodyRadius: 0.5,
      damage: 18,
    },
    crystalDrake: {
      health: 190,
      patrolSpeed: 0.95,
      chaseSpeed: 2.85,
      noticeDistance: 24,
      leashRadius: 28,
      bodyRadius: 0.64,
      damage: 19,
    },
    celestialWatcher: {
      health: 135,
      patrolSpeed: 1.28,
      chaseSpeed: 3.25,
      noticeDistance: 27,
      leashRadius: 30,
      bodyRadius: 0.42,
      damage: 16,
    },
    reefStalker: {
      health: 160,
      patrolSpeed: 1.06,
      chaseSpeed: 3.25,
      noticeDistance: 25,
      leashRadius: 30,
      bodyRadius: 0.52,
      damage: 18,
    },
    tideDrake: {
      health: 205,
      patrolSpeed: 0.86,
      chaseSpeed: 2.65,
      noticeDistance: 24,
      leashRadius: 28,
      bodyRadius: 0.7,
      damage: 20,
    },
    cliffTalon: {
      health: 120,
      patrolSpeed: 1.34,
      chaseSpeed: 3.75,
      noticeDistance: 28,
      leashRadius: 32,
      bodyRadius: 0.42,
      damage: 16,
    },
    saltbackBeast: {
      health: 230,
      patrolSpeed: 0.64,
      chaseSpeed: 2.2,
      noticeDistance: 22,
      leashRadius: 26,
      bodyRadius: 0.86,
      damage: 22,
    },
    deepwaterWisp: {
      health: 118,
      patrolSpeed: 1.32,
      chaseSpeed: 3.4,
      noticeDistance: 27,
      leashRadius: 30,
      bodyRadius: 0.38,
      damage: 15,
    },
    rootStalker: {
      health: 170,
      patrolSpeed: 1.02,
      chaseSpeed: 3.18,
      noticeDistance: 24,
      leashRadius: 30,
      bodyRadius: 0.52,
      damage: 18,
    },
    wildhorn: {
      health: 190,
      patrolSpeed: 0.86,
      chaseSpeed: 2.7,
      noticeDistance: 22,
      leashRadius: 28,
      bodyRadius: 0.68,
      damage: 20,
    },
    mossDrake: {
      health: 215,
      patrolSpeed: 0.78,
      chaseSpeed: 2.55,
      noticeDistance: 23,
      leashRadius: 28,
      bodyRadius: 0.72,
      damage: 21,
    },
    groveGuardian: {
      health: 250,
      patrolSpeed: 0.58,
      chaseSpeed: 2.05,
      noticeDistance: 21,
      leashRadius: 27,
      bodyRadius: 0.92,
      damage: 23,
    },
    mistFox: {
      health: 105,
      patrolSpeed: 1.42,
      chaseSpeed: 3.85,
      noticeDistance: 27,
      leashRadius: 32,
      bodyRadius: 0.36,
      damage: 15,
    },
  },
  bosses: {
    barkhideStalker: {
      name: "Barkhide Stalker",
      health: 360,
      patrolSpeed: 0.75,
      chaseSpeed: 2.45,
      chargeSpeed: 8.8,
      noticeDistance: 15,
      chargeDistance: 12,
      chargeCooldown: 4.2,
      chargeDuration: 0.72,
      recoveryDuration: 1.25,
      leashRadius: 18,
      contactDamage: 16,
      chargeDamage: 24,
    },
    icefang: {
      name: "Icefang",
      health: 460,
      patrolSpeed: 0.95,
      chaseSpeed: 2.85,
      pounceSpeed: 9.4,
      noticeDistance: 18,
      pounceDistance: 13,
      frostHowlCooldown: 6.5,
      pounceCooldown: 4.4,
      pounceDuration: 0.62,
      recoveryDuration: 1.2,
      leashRadius: 22,
      contactDamage: 18,
      chargeDamage: 28,
    },
    stormtalon: {
      name: "Stormtalon",
      health: 520,
      patrolSpeed: 1.15,
      chaseSpeed: 3.2,
      diveSpeed: 11.5,
      noticeDistance: 22,
      diveDistance: 18,
      gustDistance: 14,
      diveCooldown: 4.6,
      gustCooldown: 6.2,
      diveDuration: 0.82,
      recoveryDuration: 1.18,
      leashRadius: 26,
      contactDamage: 17,
      chargeDamage: 26,
      areaDamage: 20,
    },
    rootGuardian: {
      name: "The Root Guardian",
      health: 560,
      patrolSpeed: 0.62,
      chaseSpeed: 2.05,
      rootSlamSpeed: 7.2,
      noticeDistance: 19,
      slamDistance: 10,
      vinePulseDistance: 15,
      slamCooldown: 4.8,
      vinePulseCooldown: 6.4,
      slamDuration: 0.7,
      recoveryDuration: 1.32,
      leashRadius: 24,
      contactDamage: 18,
      chargeDamage: 24,
      areaDamage: 23,
    },
    mirejaw: {
      name: "Mirejaw",
      health: 620,
      patrolSpeed: 0.58,
      chaseSpeed: 2.1,
      chargeSpeed: 8.4,
      noticeDistance: 19,
      chargeDistance: 12,
      mudSplashDistance: 14,
      chargeCooldown: 4.9,
      mudSplashCooldown: 6.8,
      chargeDuration: 0.78,
      recoveryDuration: 1.35,
      leashRadius: 24,
      contactDamage: 20,
      chargeDamage: 28,
      areaDamage: 24,
    },
    stonehorn: {
      name: "Stonehorn",
      health: 660,
      patrolSpeed: 0.62,
      chaseSpeed: 2.18,
      chargeSpeed: 9.2,
      noticeDistance: 22,
      chargeDistance: 15,
      slamDistance: 11,
      chargeCooldown: 4.8,
      slamCooldown: 6.6,
      chargeDuration: 0.82,
      recoveryDuration: 1.28,
      leashRadius: 26,
      contactDamage: 21,
      chargeDamage: 30,
      areaDamage: 25,
    },
    infernoBehemoth: {
      name: "Inferno Behemoth",
      health: 720,
      patrolSpeed: 0.55,
      chaseSpeed: 2.0,
      chargeSpeed: 8.6,
      noticeDistance: 23,
      chargeDistance: 15,
      lavaBurstDistance: 13,
      chargeCooldown: 5.0,
      lavaBurstCooldown: 6.4,
      chargeDuration: 0.86,
      recoveryDuration: 1.42,
      leashRadius: 28,
      contactDamage: 23,
      chargeDamage: 32,
      areaDamage: 28,
    },
    astralGuardian: {
      name: "Astral Guardian",
      health: 880,
      patrolSpeed: 0.72,
      chaseSpeed: 2.35,
      phaseTwoSpeed: 2.85,
      chargeSpeed: 9.8,
      noticeDistance: 24,
      chargeDistance: 16,
      starVolleyDistance: 18,
      chargeCooldown: 4.6,
      starVolleyCooldown: 5.6,
      chargeDuration: 0.78,
      volleyDuration: 1.05,
      recoveryDuration: 1.22,
      leashRadius: 30,
      contactDamage: 25,
      chargeDamage: 36,
      areaDamage: 32,
    },
    ironhorn: {
      name: "The Ironhorn",
      health: 760,
      patrolSpeed: 0.68,
      chaseSpeed: 2.45,
      chargeSpeed: 10.2,
      noticeDistance: 25,
      chargeDistance: 17,
      stompDistance: 11,
      chargeCooldown: 4.5,
      stompCooldown: 6.0,
      chargeDuration: 0.82,
      recoveryDuration: 1.35,
      leashRadius: 34,
      contactDamage: 24,
      chargeDamage: 36,
      areaDamage: 28,
    },
    firstSentinel: {
      name: "The First Sentinel",
      health: 980,
      patrolSpeed: 0.62,
      chaseSpeed: 2.25,
      phaseTwoSpeed: 2.75,
      chargeSpeed: 9.6,
      noticeDistance: 24,
      chargeDistance: 16,
      pulseDistance: 14,
      chargeCooldown: 4.8,
      pulseCooldown: 6.2,
      chargeDuration: 0.84,
      recoveryDuration: 1.26,
      leashRadius: 30,
      contactDamage: 26,
      chargeDamage: 38,
      areaDamage: 34,
    },
    skyboundWarden: {
      name: "The Skybound Warden",
      health: 1120,
      patrolSpeed: 0.82,
      chaseSpeed: 2.55,
      phaseTwoSpeed: 3.0,
      diveSpeed: 10.8,
      noticeDistance: 26,
      diveDistance: 18,
      beamDistance: 15,
      diveCooldown: 4.4,
      beamCooldown: 5.8,
      diveDuration: 0.82,
      recoveryDuration: 1.18,
      leashRadius: 34,
      contactDamage: 27,
      chargeDamage: 40,
      areaDamage: 36,
    },
    tideboundWarden: {
      name: "The Tidebound Warden",
      health: 1180,
      patrolSpeed: 0.72,
      chaseSpeed: 2.45,
      phaseTwoSpeed: 2.95,
      surgeSpeed: 10.4,
      noticeDistance: 26,
      surgeDistance: 17,
      waveDistance: 15,
      surgeCooldown: 4.6,
      waveCooldown: 5.9,
      surgeDuration: 0.84,
      recoveryDuration: 1.24,
      leashRadius: 34,
      contactDamage: 28,
      chargeDamage: 42,
      areaDamage: 37,
    },
    ancientGrovekeeper: {
      name: "The Ancient Grovekeeper",
      health: 1240,
      patrolSpeed: 0.58,
      chaseSpeed: 2.2,
      phaseTwoSpeed: 2.7,
      rootChargeSpeed: 9.8,
      noticeDistance: 25,
      rootChargeDistance: 16,
      vinePulseDistance: 15,
      rootChargeCooldown: 4.9,
      vinePulseCooldown: 5.7,
      rootChargeDuration: 0.86,
      recoveryDuration: 1.36,
      leashRadius: 34,
      contactDamage: 29,
      chargeDamage: 42,
      areaDamage: 38,
    },
  },
  progression: {
    baseXpToLevel: 100,
    xpGrowth: 55,
    rewards: {
      target: 12,
      bullseye: 24,
      crawler: 45,
      wolf: 55,
      barkhideStalker: 120,
      hiddenPond: 85,
      ancientRuins: 110,
      trailMarkers: 70,
      cliffOverlook: 55,
      whisperGate: 30,
      whisperCaveTargets: 95,
      riverCrossing: 50,
      mountainPath: 70,
      forgottenGrove: 90,
      shrineEmber: 80,
      shrineFrost: 80,
      shrineGale: 90,
      guildTargets: 85,
      snowWolf: 70,
      iceStag: 80,
      frostCrawler: 75,
      icefang: 190,
      frostpeakTargets: 120,
      frostpeakExploration: 95,
      cliffRaptor: 75,
      tideCrawler: 65,
      windGull: 55,
      shellbackBeast: 95,
      stormtalon: 220,
      coastalTargets: 125,
      coastalExploration: 105,
      seaCaveShrine: 120,
      mistStag: 80,
      glowFox: 60,
      rootBeast: 95,
      forestWisp: 55,
      rootGuardian: 230,
      mistwoodTargets: 130,
      mistwoodTrails: 95,
      mistwoodExploration: 115,
      marshStalker: 75,
      mudCrawler: 80,
      mireBat: 60,
      swampHornbeast: 105,
      mirejaw: 245,
      blackwaterTargets: 135,
      sunkenShrineTrial: 140,
      blackwaterExploration: 120,
      blackwaterBogMarkers: 100,
      canyonStrider: 75,
      rockbackRam: 95,
      dustRaptor: 70,
      sandViper: 65,
      stonehorn: 260,
      redCanyonTargets: 145,
      echoTargets: 160,
      sunspireEcho: 150,
      echoChasmTargets: 155,
      redCanyonExploration: 130,
      ashHound: 80,
      emberDrake: 90,
      magmaCrawler: 95,
      firehornBeast: 115,
      infernoBehemoth: 300,
      ashenTargets: 150,
      ashenMechanisms: 165,
      firewatchRange: 145,
      ashenExploration: 145,
      astralStag: 110,
      crystalWyrm: 130,
      starboundHunter: 125,
      celestialWisp: 95,
      moonclawBeast: 150,
      astralGuardian: 360,
      starfallTargets: 190,
      celestialMechanisms: 180,
      starfallExploration: 170,
      plainsStag: 105,
      riverfang: 110,
      skyHawk: 90,
      frontierWolf: 115,
      stonehideGrazer: 140,
      ironhorn: 390,
      frontierTracks: 150,
      frontierTargets: 180,
      frontierExploration: 190,
      kingdomSentinel: 145,
      ruinStalker: 125,
      archiveWisp: 110,
      stoneGuardian: 165,
      firstSentinel: 460,
      lostKingdomTargets: 210,
      lostKingdomRecords: 170,
      ancientMechanisms: 190,
      lostKingdomExploration: 220,
      skyWyrm: 155,
      astralHunter: 150,
      crystalDrake: 175,
      celestialWatcher: 140,
      skyboundWarden: 540,
      celestialTargets: 235,
      celestialRecords: 200,
      celestialRelays: 230,
      celestialExploration: 260,
      reefStalker: 150,
      tideDrake: 180,
      cliffTalon: 130,
      saltbackBeast: 210,
      deepwaterWisp: 125,
      tideboundWarden: 580,
      shatteredCoastTargets: 240,
      tidalPaths: 210,
      shatteredCoastRecords: 240,
      shatteredCoastExploration: 280,
      rootStalker: 155,
      wildhorn: 165,
      mossDrake: 185,
      groveGuardian: 225,
      mistFox: 130,
      ancientGrovekeeper: 610,
      veiledWildsTargets: 250,
      veiledHiddenPaths: 230,
      veiledWildsRecords: 245,
      veiledWildsExploration: 300,
    },
    questRewards: {
      rowanTargets: { xp: 90, upgradePoints: 1, message: "Rowan nods. Your rhythm is improving." },
      rowanCreatures: { xp: 130, upgradePoints: 1, message: "Rowan marks the woods safer for now." },
      rowanLandmarks: { xp: 160, upgradePoints: 1, message: "Rowan trusts you to read the land." },
    },
  },
};
